<?php
$currentURI = substr($_SERVER['REQUEST_URI'], strpos($_SERVER['REQUEST_URI'], '/', 1) + 1);
//echo '<pre>';
//var_dump($_SESSION);
//echo '</pre>';
//
//echo '<pre>';
//var_dump(isAdmin());
//echo '</pre>';
//
?>
<!doctype html>
<html lang="en">
<head>
    <!--    CDNs-->
    <?php require './view/common/meta.phtml' ?>
    <?php require './view/common/scripts.phtml' ?>
    <title>
        <?php echo $TITLE ?? '1712687' ?>
    </title>
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light justify-content-between">
    <div class="container-fluid">
        <a class="navbar-brand" href="index.php">1712687_BuiMinhQuan</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link <?php echo $currentURI === 'player.php' ? 'active' : '' ?>" aria-current="page"
                       href="player.php">Player</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link <?php echo $currentURI === 'player.php?action=query' ? 'active' : '' ?>"
                       aria-current="page" href="player.php?action=query">Player query</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link <?php echo $currentURI === 'player.php?action=add' ? 'active' : '' ?>"
                       aria-current="page" href="player.php?action=add">Add new player</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link <?php echo $currentURI === 'club.php' ? 'active' : '' ?>"
                       href="club.php">Club</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link <?php echo $currentURI === 'club.php?action=add' ? 'active' : '' ?>"
                       aria-current="page" href="club.php?action=add">Add new club</a>
                </li>
            </ul>
            <ul class="navbar-nav ml-auto mb-2 mb-lg-0">
                <?php if (isAdmin()): ?>
                    <li class="nav-item">
                        <a class="nav-link" aria-current="page"
                           href="#">Xin chào <?php echo getUsername() ?></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" aria-current="page"
                           href="admin.php?action=logout">Đăng xuất</a>
                    </li>
                <?php endif; ?>

            </ul>
        </div>
    </div>
</nav>
<div class="container">
    <?php
    if (isset($VIEW)) {
        require $VIEW;
    }
    ?>
</div>
</body>
</html>