<style>
    <?php echo file_get_contents("public/css/admin/login.css") ?>
</style>

<div class="page-container">
    <div class="auth-form-container">
        <h4>Đăng nhập Admin</h4>
        <form id="sign-in-form">
            <div class="form-group">
                <label for="username">Tên tài khoản</label>
                <input type="text" class="form-control" id="username" placeholder="Nhập tên tài khoản">
            </div>
            <div class="form-group">
                <label for="password">Mật khẩu</label>
                <input type="password" class="form-control" id="password" placeholder="Nhập mật khẩu">
            </div>
            <button type="button" class="btn btn-primary" id="login">Đăng nhập</button>
        </form>
    </div>
</div>

<script type="text/javascript">
    <?php require_once('./public/js/admin/login.js') ?>
</script>
