<h2>Danh sách đơn đặt hàng</h2>

<div class="query-container">
    <form>
        <div class="form-row">
            <div class="form-group col">
                <label for="registerCode">Mã đăng ký đơn hàng</label>
                <input type="text" class="form-control" id="registerCode" placeholder="Mã đăng ký">
            </div>
            <div class="form-group col">
                <label for="phoneNumber">Số điện thoại khách hàng</label>
                <input type="text" class="form-control" id="phoneNumber" placeholder="Số điện thoại">
            </div>
            <div class="form-group col">
                <label for="customerName">Tên khách hàng</label>
                <input type="text" class="form-control" id="customerName" placeholder="Tên khách hàng">
            </div>
        </div>
        <div class="form-row">
            <div class="form-group col">
                <label for="status">Trạng thái</label>
                <select id="status" class="form-control">
                    <option value="" selected>Chọn trạng thái</option>
                    <?php if (isset($statuses)): ?>
                        <?php foreach($statuses as $status => $name): ?>
                            <option value="<?php echo $status ?>"><?php echo $name ?></option>
                        <?php endforeach; ?>
                    <?php endif; ?>
                </select>
            </div>
            <div class="form-group col">
                <label for="startAt">Ngày bắt đầu</label>
                <input type="date" class="form-control" id="startAt" placeholder="Ngày bắt đầu">
            </div>
            <div class="form-group col">
                <label for="finishAt">Ngày kết thúc</label>
                <input type="date" class="form-control" id="finishAt" placeholder="Ngày kết thúc">
            </div>
        </div>
        <div class="form-group d-flex flex-col align-items-end">
            <button id="query" type="button" class="btn btn-primary m-2">Tìm đơn hàng</button>
            <button id="reset" type="reset" class="btn btn-secondary m-2">Đặt lại</button>
        </div>
    </form>
</div>

<div id="result">
    <?php require './view/order/table.phtml'; ?>
</div>

<script type="text/javascript">
    <?php require './public/js/order/table.js' ?>
</script>
