<?php
/**
 * @var $data array
 * @var $row Order
 * @var $model Order
 * @var $pagination array
 */
if (isset($pagination) && isset($model)): ?>
    <?php $data = $pagination['data']; ?>
    <table class="table table-striped">
        <thead>
        <tr>
            <th scope="col">Mã đơn hàng</th>
            <th scope="col">Mã đăng ký</th>
            <th scope="col">Tên khách hàng</th>
            <th scope="col">Số điện thoại</th>
            <th scope="col">Trạng thái</th>
            <th scope="col">Ngày đặt hàng</th>
            <th></th>
        </tr>
        </thead>
        <tbody>
        <?php foreach ($data as $row): ?>
            <tr>
                <th scope="row"><?php echo $row->id ?></th>
                <td><?php echo $row->registerCode ?></td>
                <td><?php echo $row->customerName ?></td>
                <td><?php echo $row->getPhoneNumber() ?></td>
                <td><?php echo $row->getStatus() ?></td>
                <td><?php echo $row->getStartDate() ?></td>
                <td>
                    <button type="button" id="<?php echo $row->id ?>" class="btn btn-primary viewOrder">
                        Xem chi tiết
                    </button>
                </td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
    <?php require './view/common/pagination.phtml'; ?>
<?php endif; ?>
