<h1>Trang chủ</h1>
<ol start="1">
    <!--    Trang 1-->
    <li>
        <a href="index.php">Trang chủ</a>
        <p>Trang chủ của người dùng không có tài khoản:
            Hiển thị các liên kết tới các Trang 2, Trang 3 và
            Trang 4.</p>
    </li>
    <!--    Trang 2-->
    <li>
        <a href="order.php?action=create">Trang đặt dịch vụ</a>
        <p>Người dùng có thể đặt các dịch vụ sửa chữa tại nhà (không cần tài khoản).</p>
    </li>
    <!--    Trang 3-->
    <li>
        <a href="order.php?action=find">Trang xem chi tiết và cập nhật dịch đơn đặt hàng dịch vụ</a>
        <p>Người dùng có thể xem chi tiết đơn hàng đã đặt, cập nhật / huỷ thông tin đặt hàng.
            (Sử dụng mã đăng ký hệ thống đã gửi)</p>
    </li>
    <!--    Trang 4-->
    <li>
        <a href="admin.php">Trang chủ của admin</a>
        <p>Hiển thị các liên kết đến các chức năng Trang 5, 6.
            Nếu chưa đăng nhập thì hiển thị trang 7 cho phép đăng nhập.
            Tất cả chức năng sử dụng chung 1 layout,
            layout chung của hệ thống có chức năng đăng xuất.</p>
    </li>
</ol>